### ISSUE TITLE
[bug?]Foldcolumn color is abnormal

### ISSUE THREAD

**Issue by jinzhongjia** [ronisbr/nano-theme.nvim#3]
![image](https://github.com/ronisbr/nano-theme.nvim/assets/41784264/cd28c44f-3972-43fb-a98a-72ce3b71e6f6)

The color is not the same as the surrounding colors

**Comment by ronisbr** [comment]
Thanks! I forgot to add the configuration for `FoldColumn`. Can you please test?

**Comment by jinzhongjia** [comment]
thx, now it works fine
